#Info: all dates are written in the format HH:mm:ss

#wether the shutdown is enabled
active: false

#time for the server to shutdown
shutdown: "00:00:00"

#warning times
shutdownWarnings:
   - 5
   - 10
   - 30
   - 60
   - 300
   - 600
   - 1800

#Wether the physical computer should shutdown after the server did
#WARNING: on Linux and MAC this is a quite brutal shutdown (shutdown -h), so make sure there is no unsafed data that wouldn't survive a shutdown
physicalShutdown: false

#specify a physical shutdown delay (minutes)
physicalShutdownDelay: 1

#message to be displayed if the command executor does not have the required permissions
noPermission: "§cFoolish! You do not have permission to execute this command"

#Permission to abort the shutdown
permissionAbort: "autoshutdown.abort"

#Permission to enable the shutdown
permissionEnable: "autoshutdown.enable"

#Permission to reschedule the shutdown
permissionEnable: "autoshutdown.reschedule"
